### ISSUE TITLE
backtest.py import function name issue with ensemble stock trading.  

### ISSUE THREAD

**Issue by fjehlik** [AI4Finance-LLC/FinRL-Library#136]
In the "FinRL_ensemble_stock_trading_ICAIF_2020.ipynb" notebook, shouldn't the following import be changed from

from finrl.trade.backtest import BackTestStats, BaselineStats, BackTestPlot

to 

from finrl.trade.backtest import backtest_stats, get_baseline, backtest_plot
?

The second import has the correct names in the backtest.py file.

**Comment by Devastor** [comment]
Found same mistake! 

My Error was:
"from finrl.trade.backtest import BackTestStats
ImportError: cannot import name 'BackTestStats' from 'finrl.trade.backtest'"

Because of lowercase function names in "backtest.py" file. 

Need to change it to uppercase, like in the import, or change the import line to lowercase names. 

For example: "from finrl.trade.backtest import BackTestStats" to "from finrl.trade.backtest import backtest_stats"
should do the trick
