### ISSUE TITLE
Question: How to (try to) predict future day

### ISSUE THREAD

**Issue by M-Colley** [AI4Finance-LLC/FinRL-Library#160]
Hey, I was wondering how I would have to define the environment to predict a future day. So lets say I would train with data up until today (28th February 2021) and I want to see what the actions for the DOW_30 stocks should be for tomorrow. I can't seem to find any examples or a way to do this.

Thanks!

**Comment by Tarun-Khilani** [comment]
@M-Colley  so you want to predict data for next day like the OHLCV values?

**Comment by M-Colley** [comment]
Well, yeah kind of. I would like to predict which asset (i.e., stock) to buy the next day based on all the values up until today as training data.

**Comment by Tarun-Khilani** [comment]
Okay so what you can do is make the actions to decide which stock to pick next day based on current data,rather than deciding how much to put in all stocks. So simply have actions of 1d with length of number of stocks and you can have another dimension for amount of stocks as well maybe. Now how to reward is important in this and what i would suggest is reward with profit/loss of that stock

**Comment by chenliqiang1982** [comment]
@M-Colley Have you got the answer you want?

**Comment by XiaoYangLiu-FinRL** [comment]
@chenliqiang1982  I do not know why you try to question several discussions?   From the above discussion, the context was very clear, thus I closed it.
