### ISSUE TITLE
an error at " Single Stock Trading"

### ISSUE THREAD

**Issue by Aaron259** [AI4Finance-LLC/FinRL-Library#54]
Hello, I really appreciate your work.I is excellent. But when I ran the " Single Stock Trading" notebook directly without any modification, an error has occured as below 

==============Get Backtest Results===========
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-70-24958daad3f1> in <module>()
      2 now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')
      3 
----> 4 perf_stats_all = BackTestStats(account_value=df_account_value)
      5 perf_stats_all = pd.DataFrame(perf_stats_all)
      6 perf_stats_all.to_csv("./"+config.RESULTS_DIR+"/perf_stats_all_"+now+'.csv')

e:\CCXI工作\ETF投资\FinRL-Library-master\FinRL-Library-master\FinRL-Library-master\finrl\trade\backtest.py in BackTestStats(account_value)
     12 def BackTestStats(account_value):
     13     df = account_value.copy()
---> 14     df = get_daily_return(df)
     15     DRL_strat = backtest_strat(df)
     16     perf_func = timeseries.perf_stats

e:\CCXI工作\ETF投资\FinRL-Library-master\FinRL-Library-master\FinRL-Library-master\finrl\trade\backtest.py in get_daily_return(df)
     93     df["daily_return"] = df.account_value.pct_change(1)
     94     # df=df.dropna()
---> 95     sharpe = (252 ** 0.5) * df["daily_return"].mean() / df["daily_return"].std()
     96 
     97     annual_return = ((df["daily_return"].mean() + 1) ** 252 - 1) * 100

**Comment by TekpreXyz** [comment]
I think it is a good idea to merge the two files "single" and "multi" stock leaving only the multi, which is currently the most up-to-date, if someone wants to test a single, just put one value in the list. In this way it would be possible to save the time of simultaneously updating 2 substantially identical files; avoiding several mistakes

**Comment by TekpreXyz** [comment]
anyway the problem here is just that in 
now = datetime.datetime.now().strftime('%Y%m%d-%H**h**%M') <<<< we have an intruse
just change thil sine to:
now = datetime.datetime.now().strftime('%Y%m%d-%H%M') 
to fix it

**Comment by ariesvtb** [comment]
Fantastic solution, thank you as well

**Comment by dyh** [comment]
hi, maybe this is caused by the version of  pyfolio, the clue is in this file "./docker/requirements.txt", 
line 88: pyfolio @ git+https://github.com/quantopian/pyfolio@4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa

try this: 
1. pip uninstall pyfolio
2. pip install git+https://github.com/quantopian/pyfolio@4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa

the puzzle bothered me for 8 hours, good luck and let me know if it works. :D

-----------------------
my pip freeze list with python 3.6
-----------------------
absl-py==0.11.0
argon2-cffi==20.1.0
async-generator==1.10
atari-py==0.2.6
attrs==20.3.0
backcall==0.2.0
bleach==3.2.1
cachetools==4.2.0
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
cloudpickle==1.6.0
cycler==0.10.0
dataclasses==0.8
decorator==4.4.2
defusedxml==0.6.0
empyrical==0.5.5
entrypoints==0.3
future==0.18.2
google-auth==1.24.0
google-auth-oauthlib==0.4.2
grpcio==1.34.0
gym==0.18.0
idna==2.10
importlib-metadata==3.4.0
iniconfig==1.1.1
int-date==0.1.8
ipykernel==5.4.2
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.2
joblib==1.0.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.11
jupyter-console==6.2.0
jupyter-core==4.7.0
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
lxml==4.6.2
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.3.3
mistune==0.8.4
multitasking==0.0.9
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.3
notebook==6.1.6
numpy==1.19.5
oauthlib==3.1.0
opencv-python==4.5.1.48
packaging==20.8
pandas==1.1.5
pandas-datareader==0.9.0
pandocfilters==1.4.3
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
pkg-resources==0.0.0
pluggy==0.13.1
prometheus-client==0.9.0
prompt-toolkit==3.0.10
protobuf==3.14.0
psutil==5.8.0
ptyprocess==0.7.0
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyfolio @ git+https://github.com/quantopian/pyfolio@4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa
pyglet==1.5.0
Pygments==2.7.3
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.2.1
python-dateutil==2.8.1
pytz==2020.5
pyzmq==20.0.0
qtconsole==5.0.1
QtPy==1.9.0
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7
scikit-learn==0.24.0
scipy==1.5.4
seaborn==0.11.1
Send2Trash==1.5.0
six==1.15.0
stable-baselines3==0.10.0
stockstats==0.3.2
tensorboard==2.4.0
tensorboard-plugin-wit==1.7.0
terminado==0.9.2
testpath==0.4.4
threadpoolctl==2.1.0
toml==0.10.2
torch==1.7.1
tornado==6.1
traitlets==4.3.3
typing-extensions==3.7.4.3
urllib3==1.26.2
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
yfinance==0.1.55
zipp==3.4.0

**Comment by hust512** [comment]
> I think it is a good idea to merge the two files "single" and "multi" stock leaving only the multi, which is currently the most up-to-date, if someone wants to test a single, just put one value in the list. In this way it would be possible to save the time of simultaneously updating 2 substantially identical files; avoiding several mistakes

Thanks very much!  Agree.  Would work on it.
