### ISSUE TITLE
'DRLAgent' object has no attribute 'train_A2C'

### ISSUE THREAD

**Issue by jxin2618** [AI4Finance-LLC/FinRL-Library#82]
class DRLAgent:
    """Provides implementations for DRL algorithms

    Attributes
    ----------
        env: gym environment class
            user-defined class

    Methods
    -------
    train_PPO()
        the implementation for PPO algorithm
    train_A2C()
        the implementation for A2C algorithm
    train_DDPG()
        the implementation for DDPG algorithm
    train_TD3()
        the implementation for TD3 algorithm
    train_SAC()
        the implementation for SAC algorithm
    DRL_prediction()
        make a prediction in a test dataset and get results
    """

There does not exist the method train_A2C() under the class DRLAgent.  Can you help to fix it?

**Comment by spencerR1992** [comment]
Hi! We have made a few changes to the DRLAgent class which allow the future implementation of more functionality aside from the enumerated algorithms.  In order to clean up the implementation we have made changes, and demonstrated loading various models in the notebooks in notebook, (specifically the multistock notebook!) The new implementation is quite easy to read, and we think you'll like it!

**Comment by Mostafasaeed29** [comment]
env_train = env_setup.create_env_training(data = Train_df,
                                          env_class = StockPortfolioEnv)
agent = DRLAgent(env = env_train)

print("==============Model Training===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')
a2c_params_tuning = {'n_steps':5, 
  'ent_coef':0.005, 
  'learning_rate':0.0003,
  'verbose':0,
  'timesteps':50000}
model_a2c = agent.train_A2C(model_name = "A2C_{}".format(now), model_params = a2c_params_tuning) 


It is giving me :
'DRLAgent' object has no attribute 'train_A2C'
So can you help me?
